# Where to find the project custom commands.
commands_dir: null
# How and where to run your project executables
executables:
  docker-compose: docker compose
  # use yarn instead of npm
  npm: yarn
  composer:
    command: composer
    # Where should the command be executed?
    use:
      target: docker-compose
      with: ['exec', 'php']
