name: Aft - Framework
package_managers:
  node:
    manager: yarn
    priority: 0
  composer:
    priority: 200
environments:
  local:
    commands:
      yarn: {}
  docker-compose:
    commands:
      php: { 'container': 'php' }
      composer: { 'container': 'php' }
      mysql: { 'container': 'mysql' }
